{% set name = "aws-xray-sdk" %}
{% set version = "2.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b0cd972db218d4d8f7b53ad806fc6184626b924c4997ae58fc9f2a8cd1281568

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - botocore >=1.11.3
    - future
    - python >=3.4
    - wrapt
    # Requires enum34 for python <3.4 which is not supported by conda-forge anymore and therefore skipped.

test:
  imports:
    - aws_xray_sdk
    - aws_xray_sdk.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://docs.aws.amazon.com/xray-sdk-for-python/latest/reference/
  summary: The AWS X-Ray SDK for Python (the SDK) enables Python developers to record and emit information from within their applications to the AWS X-Ray service.
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - LICENSE
    - NOTICE
  dev_url: https://github.com/aws/aws-xray-sdk-python
  doc_url: https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html

extra:
  recipe-maintainers:
    - mariusvniekerk
    - BastianZim
