{% set name = "aws-xray-sdk" %}
{% set version = "2.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fc5537268cc8041f74e14077c4b4b4cef0f3de25ecef793ace63cedf87fe4a2a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - jsonpickle
    - python
    # uses pkg_resources
    - setuptools
    - requests
    - wrapt

test:
  imports:
    - aws_xray_sdk
    - aws_xray_sdk.core
    - aws_xray_sdk.core.emitters
    - aws_xray_sdk.core.exceptions
    - aws_xray_sdk.core.models
    - aws_xray_sdk.core.plugins
    - aws_xray_sdk.core.sampling
    - aws_xray_sdk.core.utils

about:
  home: https://github.com/aws/aws-xray-sdk-python
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: The AWS X-Ray SDK for Python (the SDK) enables Python developers to record and emit information from within their applications to the AWS X-Ray service.

extra:
  recipe-maintainers:
    - mariusvniekerk
