{% set name = "aws-xray-sdk" %}
{% set version = "2.13.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 911d634c23e0693f585c4cab08d43ab5177f872de416fdc8dd0fe3b170b52835

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - botocore >=1.11.3
    - python >=3.7
    - wrapt

test:
  imports:
    - aws_xray_sdk
    - aws_xray_sdk.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://docs.aws.amazon.com/xray-sdk-for-python/latest/reference/
  summary: The AWS X-Ray SDK for Python (the SDK) enables Python developers to record and emit information from within their applications to the AWS X-Ray service.
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - LICENSE
    - NOTICE
  dev_url: https://github.com/aws/aws-xray-sdk-python
  doc_url: https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html

extra:
  recipe-maintainers:
    - mariusvniekerk
    - BastianZim
