{% set name = "aws-xray-sdk" %}
{% set version = "2.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 78835fc841f03e550858f18a9973eab8618f47f22d2f59edf130578fa545a867

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - botocore >=1.11.3
    - python >=3.4
    - wrapt
    # Requires enum34 for python <3.4 which is not supported by conda-forge anymore and therefore skipped.

test:
  imports:
    - aws_xray_sdk
    - aws_xray_sdk.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://docs.aws.amazon.com/xray-sdk-for-python/latest/reference/
  summary: The AWS X-Ray SDK for Python (the SDK) enables Python developers to record and emit information from within their applications to the AWS X-Ray service.
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - LICENSE
    - NOTICE
  dev_url: https://github.com/aws/aws-xray-sdk-python
  doc_url: https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html

extra:
  recipe-maintainers:
    - mariusvniekerk
    - BastianZim
