travis:
  secure:
    BINSTAR_TOKEN: iS2ZRb4X0bphrbII+Aidv+9ccLxMcieDR5IBC1PlYx+KaMNS2owX9IxkV29UnwOYKsQksAbosOvtaFgHBIyzWM+5hTna04ibURTik8ua3oFJBuyGRbzZc+MomlL7msNs+BuNyzBNiCNluikXm41dAbyrmBzqSIi7ZF17uIADPOmgyD92ChaX+gjq2x3EC1XdiCTEYDpCupnmPPpI3N2RrCYCrjDrx7l+ZK5JTg4bAh2Czm+ZI1m4YefZbOcTky0bSZ2jnotGoo4tX8i5yACAZ7prhmYFiEOjpHyO+FHE4GX8YZznUZ+E603bA9leUaUZYu6KdgaXHfnTLgqnOJpLPy0v0qjokGf8gp+VzrdWwEXVpZk890/RyIMgnNhU+NMkBaK8RApIE9nmZFdEqDq7+xCjxDQujcYMCsXK79Mo2+jd9ffsHwx86IG2becmjVZ9uxpitsMLUq/ON1TcHUjEzs90ihNNSP07Cb3YirYJ8I08FC1MOjQSXgMUFNU4Pdu+4D+39CBAzA0cUng30DNPkd30XlBBOQ+guxBf+D7T0JXAxCfcatuoHgbGT99HJGizOvFyST5759im4xkmR0RkuHfLcMKMXvFIjXVU9+mW2BQOt6iqATgdOQ4jkRs6Q52J7EuypLSFOVJxat1ENGjhhLtvxNbC24jBqsKO0Q6gdJ0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
